sabdha = [
    "actually", "ability", "absolute", "abstract", "academic", "accepted", "accident", "accurate", "actively", "activity",
    "addition", "adequate", "adjustment", "admission", "advanced", "advantage", "adventure", "affected", "afternoon", "agreement",
    "alcohol", "algorithm", "analysis", "announce", "anything", "anywhere", "apparent", "approach", "argument", "arrested",
    "artistic", "assembly", "assessing", "assigned", "assistant", "associate", "athletic", "attached", "attempted", "attention",
    "attribute", "audience", "automatic", "available", "awareness", "backyard", "ballroom", "beautiful", "beginning", "behavior",
    "benchmark", "benefits", "birthday", "boundary", "brilliant", "broadcast", "building", "calendar", "candidate", "capability",
    "capacity", "carrying", "category", "cautious", "celebrate", "certainly", "challenge", "character", "chemical", "children",
    "classroom", "clinical", "closely", "clothing", "collective", "combined", "comfortable", "commercial", "committed", "committee",
    "community", "companion", "comparing", "complete", "composure", "comprise", "concerned", "concluded", "condition", "conducting",
    "conference", "confirmed", "confront", "confusion", "connected", "consider", "constant", "continue", "contribute", "convenient",
    "conversation", "corporate", "council", "creative", "critical", "cultural", "curiosity", "currently", "dangerous", "database",
    "decision", "declaration", "decrease", "dedicated", "defendant", "defensive", "definite", "delicate", "delivery", "demanding",
    "democracy", "dependent", "describe", "designer", "detailed", "determine", "developed", "diagnosis", "different", "difficulty",
    "dimension", "direction", "disabled", "disaster", "discovery", "discussion", "dismissal", "distance", "distinct", "diversity",
    "document", "domestic", "dramatic", "dynamics", "economics", "education", "effective", "efficient", "eighteen", "election",
    "eliminate", "emergency", "emphasis", "employed", "employee", "employer", "encounter", "endurance", "engagement", "enterprise",
    "entirely", "essential", "establish", "estimate", "evaluate", "evidence", "exchange", "executive", "existence", "expansion",
    "expensive", "explained", "explicit", "expression", "extended", "extension", "extensive", "facility", "familiar", "fantastic",
    "fascinating", "fashionable", "favorable", "feasible", "federation", "financial", "following", "football", "foremost", "formation",
    "fortunate", "foundation", "fourteen", "framework", "frequent", "friendship", "frontier", "function", "fundamental", "generally",
    "generated", "generation", "genetic", "geography", "governance", "government", "gradually", "graduate", "grandfather",
    "grassroots", "guarantee", "guidance", "happiness", "harvesting", "headquarters", "healthcare", "heights", "hesitation",
    "highlight", "historical", "homeless", "homework", "honestly", "hopefully", "horizontal", "hospital", "humanity", "hundreds",
    "hypothesis", "identity", "ignorance", "illustrate", "imaginary", "immediate", "immigrant", "important", "impossible",
    "impressive", "improved", "incident", "including", "incorrect", "increased", "independent", "indicate", "individual",
    "industrial", "industry", "inevitable", "infection", "inflation", "influence", "information", "initiative", "innocence",
    "innovation", "input", "inquiry", "inspection", "instance", "instinct", "instruction", "insurance", "integrated", "integrity",
    "intelligence", "intended", "interaction", "interest", "interior", "internal", "international", "intervention", "introduction",
    "investment", "invisible", "involved", "isolation", "knowledge", "landscape", "language", "leadership", "learning",
    "legislation", "literally", "literature", "management", "mandatory", "manufacture", "marketplace", "marketing", "massive",
    "material", "mathematics", "measurement", "mechanism", "medication", "medieval", "memorable", "memorial", "mentioned",
    "metropolitan", "microscope", "migration", "minimize", "minister", "ministry", "modernize", "momentum", "monetary", "monitoring",
    "motivation", "multimedia", "municipal", "mysterious", "narrative", "naturally", "navigation", "necessary", "negotiate",
    "networking", "nonsense", "normally", "notorious", "numerous", "objective", "obligation", "observation", "obstacle", "occasion",
    "occasionally", "occupation", "official", "ongoing", "opponent", "opportunity", "opposition", "optimistic", "organize",
    "orientation", "originally", "outcomes", "outstanding", "overcome", "overlook", "overwhelm", "ownership", "participant",
    "particular", "passenger", "patience", "pattern", "pedestrian", "penalty", "perceived", "perception", "performance",
    "permission", "perpetual", "personal", "perspective", "persistence", "physical", "pipeline", "placement", "planning",
    "political", "pollution", "population", "portfolio", "position", "positive", "possess", "possibility", "potential",
    "practical", "precedent", "precious", "preference", "preparation", "presence", "pressure", "presumably", "president",
    "prevention", "previous", "primary", "priority", "private", "probability", "problem", "procedure", "proceeding", "process",
    "productive", "profession", "professor", "profile", "progress", "project", "promise", "promising", "promotion", "properly",
    "proposal", "proposed", "prosecutor", "prospect", "protect", "protection", "protest", "prototype", "provincial", "psychology",
    "publication", "punishment", "pursuit", "qualification", "qualify", "quantity", "question", "rational", "reaction",
    "realistic", "realization", "reasonable", "recently", "recognition", "recommend", "recovery", "recruitment", "reference",
    "reflection", "regional", "regular", "regulate", "regulation", "reinforce", "rejection", "relationship", "relative",
    "relevance", "reliable", "religious", "remarkable", "remember", "repeated", "reputation", "request", "requirement", "research",
    "residence", "residential", "resistance", "resolution", "resource", "respect", "respond", "response", "responsible",
    "restaurant", "restoration", "restriction", "retirement", "revision", "revolution", "ridiculous", "rightful", "risking",
    "romantic", "satisfactory", "satisfied", "scheduled", "scholarship", "scientific", "secondary", "secretary", "security",
    "selection", "seniority", "sensitive", "separate", "sequence", "seriously", "session", "several", "sharpness", "shelter",
    "shipment", "shortage", "significant", "similarity", "situation", "slightly", "soccer", "software", "solution", "somehow",
    "somewhere", "specialist", "specific", "spectacular", "spiritual", "splitting", "spokesperson", "spontaneous", "stability",
    "standpoint", "statement", "stimulus", "strategic", "structure", "struggle", "subsequent", "substantial", "succeeding",
    "success", "suffering", "superior", "supplier", "support", "supposed", "surprise", "surrounding", "survival", "suspicion",
    "sustainable", "symmetry", "sympathy", "syndrome", "systematic", "technical", "technique", "technology", "television",
    "temperature", "temporary", "tendency", "territory", "testimony", "textbook", "thankful", "therefore", "thirteen", "thoroughly",
    "threaten", "tolerance", "tomorrow", "together", "tonight", "tradition", "traffic", "transaction", "transfer", "transition",
    "translation", "transmission", "transparent", "transport", "traveling", "treasurer", "tremendous", "tropical", "troubled",
    "ultimate", "unbelievable", "unconscious", "understanding", "underwater", "unexpected", "unfortunate", "uniform",
    "university", "unstable", "unusual", "upcoming", "vacation", "valuable", "variety", "vegetable", "vegetation", "vehicle",
    "vulnerable", "warehouse", "warrant", "widespread", "wilderness", "willingness", "withdrawal", "wonderful", "workplace",
    "yesterday", "youngster", "yourself" 
]